# Generated by Django 4.2.7 on 2023-11-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_route_travel_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Órden", "verbose_name_plural": "Órdenes"},
        ),
        migrations.AlterField(
            model_name="route",
            name="container_size",
            field=models.IntegerField(
                default=100, verbose_name="Tamaño del Contenedor"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="extra_cost",
            field=models.IntegerField(default=0, verbose_name="Costo Extra"),
        ),
        migrations.CreateModel(
            name="RouteResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(verbose_name="Índice")),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_routes_result",
                        to="core.location",
                        verbose_name="Lugar de destino",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_routes_result",
                        to="core.location",
                        verbose_name="Lugar de origen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderOptimized",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optimized_routes",
                    models.ManyToManyField(
                        related_name="orders_optimized",
                        to="core.route",
                        verbose_name="Rutas Optimizadas",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimizeds",
                        to="core.order",
                        verbose_name="Órden",
                    ),
                ),
            ],
        ),
    ]
