# Generated by Django 4.2.7 on 2023-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_order_options_alter_route_container_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderoptimized",
            name="optimized_routes",
            field=models.ManyToManyField(
                related_name="orders_optimized",
                to="core.routeresult",
                verbose_name="Rutas Optimizadas",
            ),
        ),
    ]
