# Generated by Django 4.2.7 on 2023-11-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_orderoptimized_optimized_routes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderoptimized",
            old_name="optimized_routes",
            new_name="routes",
        ),
    ]
