# Generated by Django 4.2.7 on 2023-11-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_optimized_routes_orderoptimized_routes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderoptimized",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optimized",
                to="core.order",
                verbose_name="Orden",
            ),
        ),
    ]
