# Generated by Django 4.2.7 on 2023-11-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderoptimized_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoptimized',
            name='solved',
            field=models.BooleanField(default=True, verbose_name='Solucionado'),
        ),
    ]
