# Generated by Django 4.2.7 on 2023-11-23 17:27

import apps.core.models.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_orderoptimized_solved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AlterField(
            model_name="order",
            name="commodity",
            field=models.CharField(
                max_length=255,
                validators=[apps.core.models.validations.validate_letters],
                verbose_name="Mercancía",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="value",
            field=models.IntegerField(verbose_name="Valor de la mercancía"),
        ),
        migrations.AlterField(
            model_name="route",
            name="carrier",
            field=models.CharField(
                max_length=255,
                validators=[apps.core.models.validations.validate_letters],
                verbose_name="Transportista",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="container_size",
            field=models.IntegerField(
                default=1000, verbose_name="Tamaño del Contenedor"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="custom_clearance_time",
            field=models.IntegerField(
                default=0, verbose_name="Tiempo de Despacho Aduanero"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="extra_time",
            field=models.IntegerField(default=0, verbose_name="Tiempo Extra"),
        ),
        migrations.AlterField(
            model_name="route",
            name="fixed_freight_cost",
            field=models.IntegerField(default=0, verbose_name="Costo Fijo"),
        ),
        migrations.AlterField(
            model_name="route",
            name="handling_time",
            field=models.IntegerField(
                default=0,
                verbose_name="Tiempo de Manejo de Puerto/Aeropuerto/Estación de Tren",
            ),
        ),
    ]
